stages:
  - deploy

pip-package:
  stage: deploy
  image: python:3.9
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm
    - pdm config python.use_venv false
  script:
    - >
      pdm publish --verbose
      --username "__token__"
      --password "$PYPI_API_TOKEN"
